[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "api_service"
version = "0.1.0"
description = "FastAPI backend API"
requires-python = ">=3.12"


dependencies = [

    # API framework
    "fastapi>=0.110",
    "uvicorn[standard]>=0.29",

    # Database
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.1",

    # Validation/config
    "pydantic>=2.0",
    "pydantic-settings>=2.0",

    # Shared package
    "basic-common",

]


[tool.setuptools.packages.find]
where = [
    "src"
]


[tool.uv.sources]
basic-common = {
    path = "../common",
    editable = true
}